input {
  file {
    path => "/var/log/app/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => plain { charset => "UTF-8" }
    tags => ["logguard"]
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:log_message}"
    }
    tag_on_failure => ["_grokparsefailure"]
  }

  date {
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss,SSS", "yyyy-MM-dd HH:mm:ss"]
    target => "@timestamp"
    remove_field => ["timestamp"]
  }

  mutate {
    add_field => { "service" => "logguard-app" }
    add_field => { "environment" => "production" }
  }

  if [level] == "ERROR" {
    mutate { add_tag => ["alert"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logguard-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
