apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: logguard
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false

  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: LogGuard
        orgId: 1
        folder: LogGuard
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        options:
          path: /etc/grafana/provisioning/dashboards
